### ISSUE TITLE
geolocate button

### ISSUE THREAD

**Issue by Sebroberts** [Esri/playlist-storytelling-template-js#24]
the ability to enable a geolocate button in the config file would be a nice feature

**Comment by ssylvia** [comment]
In order to keep the configuration simple, we are not planning to implement this feature in the near future because this is not a widely requested feature. We encourage you to download the developer version and use the geolocate button the dijit included in the JavaScript API: https://developers.arcgis.com/javascript/jsapi/locatebutton-amd.html

**Comment by Sebroberts** [comment]
Stephen,
  Thanks for your response.  I've done a reasonable amount of development with the Esri javascript API, making my own simple web apps and customizing Esri templates, and have added geolocation buttons to both of these in the past.  However, with the newer dojo AMD pattern, the lack of documentation in the code, the requirement to install GIT, Ruby, Ruby Dev Kit, and Node, I feel like the learning curve and time investment has become too steep and I am no longer able to make modifications to the templates.  I had a similar experience recently trying to make some simple modifications to the latest Find, Edit, Filter template.  I realize the design patters and coding discipline of the 2011 era templates were perhaps not as disciplined, but they sure were easier to interpret and step through for a mortal human.
Regards,
Sebastian Roberts
